version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart:
      always
  server:
    image: node:14
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "yarn && yarn run server"
    ports:
      - 3001:3001
      - 1235:1235
    expose:
      - 3001
      - 1235
      - 6060
      - 80